#!/usr/bin/env bash
set -euo pipefail

# Ghostty shader installer for RLIAMP visual atmosphere.
# Default behavior installs shader files only (no global Ghostty config changes).
#
# Usage:
#   ./scripts/ghostty-shader-import.sh
#   ./scripts/ghostty-shader-import.sh --profile neon
#   ./scripts/ghostty-shader-import.sh --profile crisp --global

PROFILE="crisp"
APPLY_GLOBAL=0
REPO_URL="${REPO_URL:-https://github.com/0xhckr/ghostty-shaders}"

DATA_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/ghostty/shaders/rliamp-scoped"

BEGIN_MARK="# >>> RLIAMP-GHOSTTY-SHADERS >>>"
END_MARK="# <<< RLIAMP-GHOSTTY-SHADERS <<<"

usage() {
  cat <<'EOF'
Usage:
  ./scripts/ghostty-shader-import.sh [--profile crisp|balanced|neon] [--global]

Options:
  --profile <name>  Shader profile to install (default: crisp)
  --global          Also write custom-shader lines to ~/.config/ghostty/config
                    (not recommended; this affects all Ghostty sessions)
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)
      PROFILE="${2:-}"
      shift 2
      ;;
    --global)
      APPLY_GLOBAL=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1"
      usage
      exit 1
      ;;
  esac
done

case "$PROFILE" in
  crisp)
    SHADERS=(
      "sin-interference.glsl"
      "dither.glsl"
    )
    ;;
  balanced)
    SHADERS=(
      "crt.glsl"
      "sin-interference.glsl"
    )
    ;;
  neon)
    SHADERS=(
      "crt.glsl"
      "glow-rgbsplit-twitchy.glsl"
      "bloom.glsl"
      "sin-interference.glsl"
    )
    ;;
  *)
    echo "Unknown profile: $PROFILE"
    echo "Supported profiles: crisp, balanced, neon"
    exit 1
    ;;
esac

tmp_dir="$(mktemp -d)"
cleanup() {
  rm -rf "$tmp_dir"
}
trap cleanup EXIT

echo "[1/3] Downloading shader pack..."
git clone --depth 1 "$REPO_URL" "$tmp_dir/repo" >/dev/null

echo "[2/3] Installing shader files..."
mkdir -p "$DATA_DIR"
for shader in "${SHADERS[@]}"; do
  src="$tmp_dir/repo/$shader"
  dst="$DATA_DIR/$shader"
  if [[ ! -f "$src" ]]; then
    echo "Missing shader in upstream pack: $shader"
    exit 1
  fi
  cp "$src" "$dst"
done

if [[ "$APPLY_GLOBAL" -eq 1 ]]; then
  CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/ghostty"
  CONFIG_FILE="$CONFIG_DIR/config"
  mkdir -p "$CONFIG_DIR"
  touch "$CONFIG_FILE"

  filtered="$tmp_dir/config.filtered"
  awk -v begin="$BEGIN_MARK" -v end="$END_MARK" '
    index($0, begin) { in_block = 1; next }
    index($0, end)   { in_block = 0; next }
    !in_block        { print }
  ' "$CONFIG_FILE" >"$filtered"

  {
    cat "$filtered"
    echo
    echo "$BEGIN_MARK"
    echo "# Auto-generated by rliamp/scripts/ghostty-shader-import.sh"
    echo "# Profile: $PROFILE"
    for shader in "${SHADERS[@]}"; do
      echo "custom-shader = $DATA_DIR/$shader"
    done
    echo "$END_MARK"
  } >"$CONFIG_FILE"
fi

echo "[3/3] Done."
echo "Shaders installed: $DATA_DIR"
echo "Profile: $PROFILE"
if [[ "$APPLY_GLOBAL" -eq 1 ]]; then
  echo "Global Ghostty config updated: $CONFIG_FILE"
else
  echo "No global Ghostty config was modified."
fi
echo "Use scoped launch (recommended):"
echo "  ./scripts/run-rliamp-ghostty.sh --profile $PROFILE /path/to/song.mp3"
