#!/usr/bin/env bash
set -euo pipefail

# One-shot Ghostty shader importer for RLIAMP visual atmosphere.
# Usage:
#   ./scripts/ghostty-shader-import.sh           # default: neon
#   ./scripts/ghostty-shader-import.sh balanced  # milder effect

PROFILE="${1:-neon}"
REPO_URL="${REPO_URL:-https://github.com/0xhckr/ghostty-shaders}"

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/ghostty"
CONFIG_FILE="$CONFIG_DIR/config"
SHADER_DIR="$CONFIG_DIR/shaders/rliamp"

BEGIN_MARK="# >>> RLIAMP-GHOSTTY-SHADERS >>>"
END_MARK="# <<< RLIAMP-GHOSTTY-SHADERS <<<"

case "$PROFILE" in
neon)
  SHADERS=(
    "crt.glsl"
    "glow-rgbsplit-twitchy.glsl"
    "bloom.glsl"
    "sin-interference.glsl"
  )
  ;;
balanced)
  SHADERS=(
    "crt.glsl"
    "glow-rgbsplit-twitchy.glsl"
    "bloom.glsl"
  )
  ;;
*)
  echo "Unknown profile: $PROFILE"
  echo "Supported profiles: neon, balanced"
  exit 1
  ;;
esac

tmp_dir="$(mktemp -d)"
cleanup() {
  rm -rf "$tmp_dir"
}
trap cleanup EXIT

echo "[1/4] Downloading shader pack..."
git clone --depth 1 "$REPO_URL" "$tmp_dir/repo" >/dev/null

echo "[2/4] Installing shader files..."
mkdir -p "$SHADER_DIR"
for shader in "${SHADERS[@]}"; do
  src="$tmp_dir/repo/$shader"
  dst="$SHADER_DIR/$shader"
  if [[ ! -f "$src" ]]; then
    echo "Missing shader in upstream pack: $shader"
    exit 1
  fi
  cp "$src" "$dst"
done

mkdir -p "$CONFIG_DIR"
touch "$CONFIG_FILE"

echo "[3/4] Writing Ghostty config block..."
filtered="$tmp_dir/config.filtered"
awk -v begin="$BEGIN_MARK" -v end="$END_MARK" '
  $0 == begin { in_block = 1; next }
  $0 == end   { in_block = 0; next }
  !in_block   { print }
' "$CONFIG_FILE" >"$filtered"

{
  cat "$filtered"
  echo
  echo "$BEGIN_MARK"
  echo "# Auto-generated by rliamp/scripts/ghostty-shader-import.sh"
  echo "# Profile: $PROFILE"
  for shader in "${SHADERS[@]}"; do
    echo "custom-shader = $SHADER_DIR/$shader"
  done
  echo "$END_MARK"
} >"$CONFIG_FILE"

echo "[4/4] Done."
echo "Ghostty shaders are enabled."
echo "Config: $CONFIG_FILE"
echo "Shaders: $SHADER_DIR"
echo "Restart Ghostty or open a new Ghostty window to apply."
